# Generated by Django 4.2.4 on 2023-08-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("message", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[
                    ("Решено", "Complete"),
                    ("Ожидает", "Waiting"),
                    ("Нет решения", "Unresolved"),
                ],
                default="Ожидает",
                max_length=16,
            ),
        ),
    ]
