# Generated by Django 4.2.4 on 2023-08-24 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0002_feedbackuser_message_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="feedbackuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("Решено", "Complete"),
                    ("Ожидает", "Waiting"),
                    ("Нет решения", "Unresolved"),
                ],
                default="Ожидает",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="feedbackuser",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
