# Generated by Django 4.2.4 on 2023-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0003_remove_message_chat_remove_message_sender_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackuser",
            options={
                "verbose_name": "Заявка обратной связи",
                "verbose_name_plural": "Заявки обратной связи",
            },
        ),
        migrations.AlterField(
            model_name="feedbackuser",
            name="message",
            field=models.TextField(verbose_name="Проблема"),
        ),
        migrations.AlterField(
            model_name="feedbackuser",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="feedbackuser",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="Номер телефона"),
        ),
        migrations.AlterField(
            model_name="feedbackuser",
            name="status",
            field=models.CharField(
                choices=[
                    ("Решено", "Complete"),
                    ("Ожидает", "Waiting"),
                    ("Нет решения", "Unresolved"),
                ],
                default="Ожидает",
                max_length=16,
                verbose_name="Статус ответа на заявку",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackuser",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата заявки"),
        ),
    ]
