# Generated by Django 4.2.4 on 2023-08-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("messanger", "0004_alter_feedbackuser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackuser",
            name="timestamp",
            field=models.DateTimeField(verbose_name="Дата заявки"),
        ),
    ]
